name: Gestao de Vagas Application

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21
      - name: Build project
        run: mvn clean install
      - name: Login Docker
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USER }}/gestao_vagas .
      - name: Publish image
        run: docker push ${{ secrets.DOCKER_USER }}/gestao_vagas

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image Docker Hub
        run: docker pull ${{ secrets.DOCKER_USER }}/gestao_vagas:latest
      - name: Remove container
        run: docker rm -f gestao_vagas
      - name: Run Docker container gestao_vagas
        run: docker run -d -p 8080:8080 ${{ secrets.DOCKER_USER }}/gestao_vagas:latest